### ISSUE TITLE
improve current APIs

### ISSUE THREAD

**Issue by DynamicGoose** [DynamicGoose/magma-api#13]
### Todo
- [ ] take number of windows to be spawned in `spawn` method `magma_winit`
- [ ] testing event workflow `magma_winit`
- [ ] real ui implementation
- [ ] better audio workflow (maybe move away from `kira` to a more low levl library)

**Comment by DynamicGoose** [comment]
#15
